# Source language and JDK version to use
language: java
jdk: oraclejdk7

# Compile and package JAR and set build properties
install: gradle setupCIWorkspace
script: gradle build -PbuildNumber=$TRAVIS_BUILD_NUMBER -PciSystem=travis -Pcommit=${TRAVIS_COMMIT:0:7}

# Perform steps after compilation/test success
after_success:
  # Generate Cobertura report for Coveralls.io
  - "gradle cobertura coveralls -PserviceJobId=$TRAVIS_JOB_ID"
  # Check if commit s not a pull request, if git repo is official, and if branch is master. If checks pass, add libs and deploy artifacts to Maven repository.
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == ObsidianBox/Obsidian ]] && [[ $TRAVIS_BRANCH == master ]] && ./gradlew uploadArchives"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  webhooks:
    # Send build information and status to Notifico
    - http://n.tkte.ch/h/2909/F2YRRWsmXlSab_It7DfM4TMb

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
    # Super secure, encrypted variables! Ssssh!
    - secure: "PNefD/xS3Pvu6Xj95UIzyHVScXhT3cQdr96Pt6t6iAhlBORahbEDeT28+ZrjX5lyD6MTZZQKJ3rmpEpGfkPKuqsPJ7zis/mGoPddGaRghZwxc3mEJIaToTKcDPGBz0EUn4hTmF7Sn7Prcjye883edq/gnWOuqCk4NxMBo33v9SI="
    - secure: "dTqb1cdj3p7K6lY4ZVA4ki67wYjK5N+kRccJ2dJ8ZbYB+uy3Rgq0YXCVHm+A7a8F7KydJOHx4v/vq3dYnctgjRALlW2Ka76rXWDiMHNV+bbp7tjkiVEJImzprDE4rQFdzKyDoAV4D+tK0ZOvwaj424DAKh90eMfkALkMEe2ejEc="
